services:
  # auth-mongo:
  #   image: mongo
  #   ports:
  #     - 27099:27017
  #   networks:
  #     - app-network  
  #   volumes:
  #     - data-node:/data/db
  auth-serv:
    image: node:16-alpine
    env_file: .env
    command: sh -c "npm install --omit=dev && npm start"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGO_URI: ${MONGO_URI}
      DOCTYPE: ${DOCTYPE}
      JWT_KEY: ${JWT_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      WHITELIST_CORS: ${WHITELIST_CORS}
    # depends_on:
    #   - auth-mongo
#     networks:
#       - app-network  
# networks:
#   app-network:
#     driver: bridge
# volumes:
#   data-node: